# GitHub Pages Configuration for Sina
title: "Sina - Your Disciplined Mentor"
description: "Build unshakeable discipline through task management, focus sessions, journaling, and personalized mentorship."
url: "https://prisden.github.io"
baseurl: "/Sina"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude files from processing
exclude:
  - README.md
  - CHANGELOG.md
  - BUG_REPORT.md
  - DEPLOYMENT.md
  - requirements.txt
  - app.py
  - wsgi.py
  - deploy.py
  - backup_data.py
  - migrate_to_postgres.py
  - Procfile
  - runtime.txt
  - start_sina.*
  - templates/
  - static/
  - instance/
  - __pycache__/
  - venv/
  - logs/
  - .git/
  - .gitignore

# Include files
include:
  - _redirects

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Site settings
author: "Sina Team"
email: "hello@sina.app"
github_username: "PrisDen"

# Social media
social:
  name: "Sina - Your Disciplined Mentor"
  links:
    - "https://github.com/PrisDen/Sina"

# SEO
lang: en_US
timezone: UTC 